version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn parking.wsgi:application --bind 0:8000"
    depends_on:
      - db
    volumes:
      - static_value:/app/static_files/
      - media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_files/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  postgres:
  static_value:
  media_value:


